// 'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header, Footer, Menu } from '@/components'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import { GlobalContextProvider } from '@/Context/store';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header/>
//         {children}
//       </body>
//     </html>
//   )
// }

export function generateStaticParams() {
  return [{locale: 'uz'}, {locale: 'en'}, {locale: 'ru'}];
}

export default async function LocaleLayout({children, params: {locale}}:{children : React.ReactNode, params : any}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
 
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <GlobalContextProvider>
            <Menu/>
            <Header/>
              {children}
            <Footer/>
          </GlobalContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
